@startuml

title System Blocks

hide circle
hide empty members
hide method

package "Cage" as NodeCage <<node>>{
  class "MoblieDevice" as BlockMobileDevice <<block>>{
  }
  
  class "TemperatureMeasureUnit" as BlockTemperatureMeasureUnit <<block>>{
  }
  
  class "MainControlUnit" as BlockMainControlUnit <<block>>{
  }
  
  class "UVLight" as BlockUVLight <<block>>{
  }
  
  class "ThermoHeater" as BlockThermoHeater <<block>>{
  }
}
class "DataServer" as BlockDataServer <<block>>{
}

BlockMobileDevice -- BlockDataServer : internet 
BlockMainControlUnit -- BlockDataServer : internet
BlockMainControlUnit -- BlockTemperatureMeasureUnit : twilight
BlockMainControlUnit -- BlockThermoHeater : AC100VCalble
BlockMainControlUnit -- BlockUVLight : AC100VCalble


@enduml

