#ifndef _WEBSERVERFORMHTML_H_
#define _WEBSERVERFORMHTML_H_

#include <Arduino.h>
#include <time.h>

const String Form_WiFiSetting = 
"<h1>Wi-Fi Settings</h1>"
"<form method='post'>"
"  <input type='text' name='ssid' placeholder='ssid'><br>"
"  <input type='text' name='pass' placeholder='pass'><br>"
"  <input type='submit'><br>"
"</form>";

const String SettingSentPage = 
"<h1>Wi-Fi Settings sent</h1>";

const String Form_SystemControl =
"<h1>System Control</h1>"
"<form method='post'>"
"  <input type='submit'><br>"
"  <h2>Mode Selection</h2>"
"  <select name='mode'>"
"    <option value='FULL_AUTO'>full auto</option>"
"    <option value='SEMI_AUTO'>semi auto</option>"
"    <option value='FULL_MANUAL'>full manual</option>"
"  </select>"
"  <h2>Switch Setting</h2>"
"  <span>"
"    Heater Switch"
"    <select name='heaterswitch'>"
"      <option value='ON'>ON</option>"
"      <option value='OFF'>OFF</option>"
"    </select>"
"  </span>"
"  <br>"
"  <span>"
"    Fan Switch"
"    <select name='fanswitch'>"
"      <option value='ON'>ON</option>"
"      <option value='OFF'>OFF</option>"
"    </select>"
"  </span>"
"  <br>"
"  <span>"
"    UV Switch"
"    <select name='uvswitch'>"
"      <option value='ON'>ON</option>"
"      <option value='OFF'>OFF</option>"
"    </select>"
"  </span>"
"  <h2>Temp Table setting</h2>"
"  <span>"
"    table1"
"    <input type='text' name='time1' placeholder='time1'>"
"    <input type='text' name='temp1' placeholder='temp1'>"
"  </span>"
"  <br>"
"  <span>"
"    table2"
"    <input type='text' name='time2' placeholder='time2'>"
"    <input type='text' name='temp2' placeholder='temp2'>"
"  </span>"
"  <br>"
"  <span>"
"    table3"
"    <input type='text' name='time3' placeholder='time3'>"
"    <input type='text' name='temp3' placeholder='temp3'>"
"  </span>"
"  <br>"
"  <span>"
"    table4"
"    <input type='text' name='time4' placeholder='time4'>"
"    <input type='text' name='temp4' placeholder='temp4'>"
"  </span>"
"  <br>"
"  <span>"
"    table5"
"    <input type='text' name='time5' placeholder='time5'>"
"    <input type='text' name='temp5' placeholder='temp5'>"
"  </span>"
"  <br>"
"  <span>"
"    table6"
"    <input type='text' name='time6' placeholder='time6'>"
"    <input type='text' name='temp6' placeholder='temp6'>"
"  </span>"
"  <br>"
"  <span>"
"    table7"
"    <input type='text' name='time7' placeholder='time7'>"
"    <input type='text' name='temp7' placeholder='temp7'>"
"  </span>"
"  <br>"
"  <span>"
"    table8"
"    <input type='text' name='time8' placeholder='time8'>"
"    <input type='text' name='temp8' placeholder='temp8'>"
"  </span>"
"  <h2>UV Table Setting</h2>"
"  <span>"
"    <input type='text' name='uvOnStartTime' placeholder='OnTimeStart'>"
"    <input type='text' name='uvOnEndTime' placeholder='OnTimeEnd'>"
"  </span>"
"</form>";

String CreateCurrentStatusHTML(String nameOfMode, double currentTemp, String nameOfEnvironmentJudge, time_t currentTime, byte switchState);


#endif