#ifndef FORMATINFO_H_
#define FORMATINFO_H_

#define COMMAND_BYTE_SIZE 1
#define RESPONSE_BYTE_SIZE 1
#define DATA_BYTE_SIZE 64
#define CHECKSUM_BYTE_SIZE 1
#define FULL_PACKET_SIZE (COMMAND_BYTE_SIZE + RESPONSE_BYTE_SIZE + DATA_BYTE_SIZE + CHECKSUM_BYTE_SIZE)

#define COMMAND_CODE_POS 0
#define RESPONSE_POS (COMMAND_CODE_POS + COMMAND_BYTE_SIZE)
#define DATA_START_POS (RESPONSE_POS + RESPONSE_BYTE_SIZE)
#define DATA_END_POS (DATA_START_POS + DATA_BYTE_SIZE - 1)
#define CHECKSUM_POS (FULL_PACKET_SIZE - 1)


#endif