@startuml

title Block Diagram 

hide circle
hide method
hide empty members


class "WiFiMCU" as BlockWiFiMCU  <<block>>{
}
class "ADC" as BlockADC <<block>>{
}
class "PowerCircuit" as BlockPowerCircuit <<block>>{
}
class "ACSwitchCircuit" as BlockACSwitchCircuit <<block>>{
}
class "LCDIndicator" as BlockLCDIndicator <<block>>{
}
class "ResistiveDividor" as BlockResistiveDividor <<block>>{
}
class "Thermistor" as BlockThermistor <<block>>{
}

'WifiMCUとADCはI2Cで接続
BlockWiFiMCU -- BlockADC : I2C

'WifiMCUには3.3Vを供給
BlockWiFiMCU -- BlockPowerCircuit : DC3.3V

BlockWiFiMCU "1"--"3" BlockACSwitchCircuit : GPIO

'WifiMCUとLCDはI2Cで接続
BlockWiFiMCU -- BlockLCDIndicator : I2C

'LCDには5Vを供給
BlockPowerCircuit -- BlockLCDIndicator : DC5V

'ResistiveDividorには3.3Vを供給
BlockPowerCircuit -- BlockResistiveDividor : DC3.3V

'ADCには3.3Vを供給
BlockPowerCircuit -- BlockADC : DC3.3V

'ADCに, ResistiveDividorの入力をキャプチャさせる
BlockADC -- BlockResistiveDividor : Analog Signal Line

'ResistiveDividorに, サーミスタを接続
BlockResistiveDividor -- BlockThermistor : Analog Signal Line
@enduml
