@startuml

title Usecase Diagram

left to right direction

actor User as ActorUser



package ControlBox{
}

package Server{
  usecase "DDNS機能" as UsecaseDDNS
  usecase "NTPで時刻補正機能" as UsecaseNTPTimeCalibration
  usecase "ControlBoxから送信されたデータの蓄積" as UsecaseDataLogging
  usecase "ControlBoxから一定時間データが来ない場合通知" as UsecaseNotifyControlBoxSilent
  usecase "各種データ表示および制御" as UsecaseRemoteControlAndWatch
  
  UsecaseRemoteControlAndWatch <.. UsecaseDDNS : <<include>>
  UsecaseDataLogging <.. UsecaseNTPTimeCalibration : <<include>>
}

package PHPonServer{
  usecase "現在温度確認" as UsecaseGetCurrentTemp
  usecase "システムの状態確認" as UsecaseGetCurrentStatus
  usecase "マニュアル制御 \n==\n 制御開始/停止 \n--\n UV On/Off \n--\n Heater On/Off \n--\n Fan On/Off" as UsecaseFullManualControl
  usecase "温度の推移をグラフ視認" as UsecaseIndicateGraph
  usecase "ControlBoxの初期設定" as UsecaseSetupControlBox
} 

ActorUser -- UsecaseRemoteControlAndWatch : WebBrowser
ActorUser -- UsecaseNotifyControlBoxSilent : SNS notify

UsecaseRemoteControlAndWatch o-- UsecaseGetCurrentTemp
UsecaseRemoteControlAndWatch o-- UsecaseGetCurrentStatus
UsecaseRemoteControlAndWatch o-- UsecaseFullManualControl
UsecaseRemoteControlAndWatch o-- UsecaseIndicateGraph
UsecaseRemoteControlAndWatch o-- UsecaseSetupControlBox
@enduml
