@startuml

title Usecase Diagram

left to right direction

actor User as ActorUser

actor Cage as ActorCage

node "制御ボード"{
  usecase "システムONOFF" as UsecaseSystemONOFF

  usecase "環境制御" as UsecaseControlEnvironment

  usecase "フルオート制御" as UsecaseFullAutoControl

  usecase "セミオート制御" as UsecaseSemiAutoControl

  usecase "マニュアル制御" as UsecaseManualControl

  UsecaseControlEnvironment <|-down-- UsecaseFullAutoControl
  UsecaseControlEnvironment <|-down- UsecaseSemiAutoControl
  UsecaseControlEnvironment <|-down- UsecaseManualControl

  usecase "動作設定\n==\nextension points\n設定方法" as UsecaseSetting

  usecase "ブラウザから設定" as UsecaseSettingWithBrowser

  UsecaseSetting ..> UsecaseSettingWithBrowser : <<extend>>

  usecase "ヒータ制御" as UsecaseControlHeater

  usecase "UV制御" as UsecaseControlUV

  usecase "Fan制御" as UsecaseControlFan

  usecase "温度測定" as UsecaseMeasureTemperature 

  UsecaseControlEnvironment <.up. UsecaseControlHeater : <<include>>
  UsecaseControlEnvironment <.up. UsecaseControlUV : <<include>>
  UsecaseControlEnvironment <.up. UsecaseControlFan : <<include>>
  UsecaseControlEnvironment <.up. UsecaseMeasureTemperature : <<include>>
}

ActorUser -- UsecaseSystemONOFF
ActorUser -- UsecaseSetting

UsecaseControlEnvironment -- ActorCage

@enduml
